# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# https://github.com/normanlorrain/mkdocs-thumbnails
# https://squidfunk.github.io/mkdocs-material/reference/admonitions
# https://squidfunk.github.io/mkdocs-material/reference/images
# https://blueswen.github.io/mkdocs-glightbox/caption/caption


site_name: Brownian Movement
site_description: "Engineering when you're too bored"
site_author: Maxim Devaev
site_url: https://mdevaev.github.io/brownian.mov

repo_name: mdevaev/brownian.mov
repo_url: https://github.com/mdevaev/brownian.mov
edit_uri: ""

copyright: "Copyright &copy; 2025 Maxim Devaev, Iaroslav Liachin"

docs_dir: docs

theme:
    logo: _assets/logo.png
    favicon: _assets/favicon.ico
    name: material
    palette:
        primary: blue grey
    font:
        text: "arial, sans-serif"
        code: monospace
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - navigation.expand
        - search.highlight
        - search.share
        - search.suggest
    custom_dir: overrides

extra_css:
    - _assets/user.css

markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.blocks.caption
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs

plugins:
    - blog:
        post_url_format: "posts/{slug}"
        post_url_date_format: yyyy/MM/dd
        blog_toc: true
    - search:
        lang: en
    - mkdocs-video
    - redirects:
        redirect_maps: {}
    - glightbox:
        touchNavigation: false
        loop: false
        slide_effect: slide
        width: 95%
        height: auto
        zoomable: true
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: true
        manual: false
#    - rss:
#        use_git: false
#        match_path: "blog/posts/*" 
#        date_from_meta:
#            as_creation: date
#        categories:
#            - categories

nav:
    - "Mainpage":
        - index.md
    - "Blog":
        - blog/index.md
    - "Big projects":
        - "PiKVM Project": https://pikvm.org
    - "Links":
        - "Twitter": https://x.com/mdevaev
        - "YouTube": https://www.youtube.com/@amt9216
        - "Telegram (ru)": https://t.me/chaotic_diy
